apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: petclinicback
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
  type: ClusterIP
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicback
  labels:
    app: petclinicback
spec:
  replicas: 1
  selector:
    matchLabels:
    app: petclinicback
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:    
    metadata:
      labels:
        app: petclinicback
    spec:
      containers:
      - name: petclinicback
        image: mfroy/petclinicback
        ports:
        - containerPort: 9966    