apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
  type: ClusterIP
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
    app: backend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:    
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: petclinicback
        ports:
        - containerPort: 9966    