apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: petclinicfront
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9966
  type: ReverseProxy
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicfront
  labels:  
  app: petclinicfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinicfront
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    template:
      metadata:
      labels:
        app: petclinicfront
      spec:
        containers:
        - name: petclinicfront
        image: mfroy/pectclinicfront
        ports:
        - containerPort: 5000      
